// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPolOcQmKi7kyXHBX_fPt0ZyzQSG87Sx4',
    appId: '1:952968117213:web:a569a6cda745e262aa9434',
    messagingSenderId: '952968117213',
    projectId: 'spac-d80e2',
    authDomain: 'spac-d80e2.firebaseapp.com',
    storageBucket: 'spac-d80e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxRHpZLrWK5TnTJRN6Rg7BdLExs7vzz6Q',
    appId: '1:952968117213:android:d4bf1764af03b433aa9434',
    messagingSenderId: '952968117213',
    projectId: 'spac-d80e2',
    storageBucket: 'spac-d80e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEFG475nGoxdivbpkQLwlkg3s8GahDDzI',
    appId: '1:952968117213:ios:78894d7d07adcd40aa9434',
    messagingSenderId: '952968117213',
    projectId: 'spac-d80e2',
    storageBucket: 'spac-d80e2.appspot.com',
    iosBundleId: 'com.example.spac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEFG475nGoxdivbpkQLwlkg3s8GahDDzI',
    appId: '1:952968117213:ios:36431e7f309e8c11aa9434',
    messagingSenderId: '952968117213',
    projectId: 'spac-d80e2',
    storageBucket: 'spac-d80e2.appspot.com',
    iosBundleId: 'com.example.spac.RunnerTests',
  );
}
